[[plugins]]
# dein用
repo = 'Shougo/dein.vim'

[[plugins]]
# fzf用
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
# ファジー検索(ファイルや単語検索)
repo = 'junegunn/fzf'
repo = 'junegunn/fzf.vim'
on_cmd = [
    'Files',
    'ProjectFiles',
    'Buffers',
    'BLines',
    'History',
    'Tags',
    'BTags',
    'GFiles',
    'Ag',
    'Rg',
]
hook_add = '''
" ripgrepより遅いため、使わない
" nnoremap <silent> <Leader>a :<C-u>Ag<CR>
nnoremap <silent> <Leader>r :<C-u>Rg<CR>
nnoremap <silent> <Leader>f :<C-u>Files<CR>
nnoremap <silent> <Leader>b :<C-u>Buffers<CR>
nnoremap <silent> <Leader>h :<C-u>History<CR>
" set rtp+=/usr/local/bin/fzf
" set rtp+=$XDG_CACHE_HOME/fzf "$XDG_CACHE_HOMEの下にインストールした場合
" set rtp+=~/.fzf "~/.fzfにインストールした場合
'''

[[plugins]]
# ファイラー
repo = 'lambdalisue/fern.vim'

[[plugins]]
# ファイラーのプレビュー
repo = 'yuki-yano/fern-preview.vim'

[[plugins]]
# AI補完
repo = 'github/copilot.vim'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
    autocmd BufRead,BufNewFile *.md  set filetype=markdown
    nnoremap <silent> <C-p> :PrevimOpen<CR>
    let g:vim_markdown_folding_disabled=1
    let g:previm_enable_realtime=1
'''

[[plugins]]
# URLをブラウザーで開く
# 追加の設定が必要(ショートカットコマンド)
repo = 'tyru/open-browser.vim'

[[plugins]]
# Linter
# 追加の設定が必要(Lintのタイミングなど)
repo = 'dense-analysis/ale'

[[plugins]]
# ステータスラインを綺麗に
repo = 'itchyny/lightline.vim'

[[plugins]]
# gitの差分を行数で表示
repo = 'airblade/vim-gitgutter'

[[plugins]]
# gitのコマンド
repo = 'tpope/vim-fugitive'

[[plugins]]
# なんか色々Tab補完
repo = 'ervandew/supertab'

[[plugins]]
# Syntax Highlight
repo = 'sheerun/vim-polyglot'

[[plugins]]
# 括弧を対にしてくれる
# いらなかったら消そう
repo = 'jiangmiao/auto-pairs'

# [[plugins]]
# # 囲みだけを削除できる
# # 追加の設定が必要(ショートカット)
# # あんまり使わなさそうだから、コメントアウト
# repo = 'tpope/vim-surround'

[[plugins]]
# カーソル移動を楽に
# 追加の設定が必要(ショートカット)
# 一番練習したい
repo = 'easymotion/vim-easymotion'

[[plugins]]
# ウィンドウのサイズを変更
repo = 'simeji/winresizer'

[[plugins]]
# 末尾のスペースの可視化と削除
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
# <C-d>と<C-u>がスムーズになる
repo = 'yuttie/comfortable-motion.vim'

[[plugins]]
# カラーテーマ
repo = 'tomasr/molokai'

[[plugins]]
# インデントを可視化
# 追加の設定が必要
repo = 'nathanaelkane/vim-indent-guides'

