[[plugins]]
# dein用
repo = 'Shougo/dein.vim'

[[plugins]]
# fzf用
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
# ファジー検索(ファイルや単語検索)
repo = 'junegunn/fzf'
repo = 'junegunn/fzf.vim'
on_cmd = [
    'Files',
    'ProjectFiles',
    'Buffers',
    'BLines',
    'History',
    'Tags',
    'BTags',
    'GFiles',
    'Ag',
    'Rg',
]

[[plugins]]
# ファイラー
repo = 'lambdalisue/fern.vim'

[[plugins]]
# ファイラーのプレビュー
repo = 'yuki-yano/fern-preview.vim'

[[plugins]]
# gitのstatusをファイラーに表示
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
# nerdfont
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
# ファイラーにアイコンをつける
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
# ファイラーのアイコンに色をつける
repo = 'lambdalisue/glyph-palette.vim'

[[plugins]]
# ファイラーにアイコンをつける
repo = 'ryanoasis/vim-devicons'

[[plugins]]
# AI補完
repo = 'github/copilot.vim'

[[plugins]]
# gitの差分を行数で表示
repo = 'airblade/vim-gitgutter'

[[plugins]]
# gitのコマンド
repo = 'tpope/vim-fugitive'

[[plugins]]
# カーソル移動を楽に
repo = 'phaazon/hop.nvim'
hook_add = '''
lua require'hop'.setup()
lua vim.api.nvim_set_keymap('n', 'f', "<cmd> lua require'hop'.hint_words({ hint_position = require'hop.hint'.HintPosition.END })<cr>", {})
lua vim.api.nvim_set_keymap('v', 'f', "<cmd> lua require'hop'.hint_words({ hint_position = require'hop.hint'.HintPosition.END })<cr>", {})
lua vim.api.nvim_set_keymap('o', 'f', "<cmd> lua require'hop'.hint_words({ hint_position = require'hop.hint'.HintPosition.END, inclusive_jump = true })<cr>", {})
'''

[[plugins]]
# コメントアウト用
repo = 'tpope/vim-commentary'

[[plugins]]
# LSP用
# 追加の設定が必要
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = '''
nnoremap <silent> g[ <Plug>(coc-diagnostic-prev)
nnoremap <silent> g] <Plug>(coc-diagnostic-next)
nnoremap <silent> gd <Plug>(coc-definition)
nnoremap <silent> gD <Plug>(coc-definition-preview)
nnoremap <silent> gr <Plug>(coc-references)
nnoremap rn <Plug>(coc-rename)
nnoremap qf <Plug>(coc-fix-current)
nnoremap <silent><nowait> <Leader>a :<C-u>CocList diagnostics<cr>
nnoremap <silent><nowait> <Leader>o :<C-u>CocList outline<cr>
# nnoremap <silent> gy <Plug>(coc-type-definition)
# nnoremap <silent> gi <Plug>(coc-implementation)
'''

[[plugins]]
# ステータスラインを綺麗に
repo = 'itchyny/lightline.vim'

[[plugins]]
# ウィンドウのサイズを変更
repo = 'simeji/winresizer'

[[plugins]]
# 簡単に選択範囲を拡大
repo = 'tpope/vim-expand-region'



[[plugins]]
# URLをブラウザーで開く
# 追加の設定が必要(ショートカットコマンド)
repo = 'tyru/open-browser.vim'

# [[plugins]]
# # なんか色々Tab補完
# # Copilotと被るので無効
# repo = 'ervandew/supertab'

[[plugins]]
# Syntax Highlight
repo = 'sheerun/vim-polyglot'

[[plugins]]
# 括弧を対にしてくれる
# いらなかったら消そう
repo = 'jiangmiao/auto-pairs'

# [[plugins]]
# # 囲みだけを削除できる
# # 追加の設定が必要(ショートカット)
# # あんまり使わなさそうだから、コメントアウト
# repo = 'tpope/vim-surround'

[[plugins]]
# 末尾のスペースの可視化と削除
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
# <C-d>と<C-u>がスムーズになる
repo = 'yuttie/comfortable-motion.vim'

[[plugins]]
# カラーテーマ
repo = 'tomasr/molokai'

[[plugins]]
# インデントを可視化
repo = 'Yggdroot/indentLine'

[[plugins]]
# コードを整理してくれる
# 追加の設定が必要(ショートカット)
repo = 'junegunn/vim-easy-align'
